### ISSUE TITLE
[new addon] date-time-adapter

### ISSUE THREAD

**Issue by tomasy** [mozilla-iot/addon-list#139]
I have created an adapter to make it easier to create rules. This adapter contains the following properties
- sunset
- sunrise
- weekend
- dark
- hour
- minutes
- even hour

Latitude, longitude, timezone and horizon is configurable

With those properties you can create a rule like
Turn the bedroom lamp on only on weekdays
`if the time of day is 06:13 and DateTime is not weekend, turn BedroomLamp on`
or
To start the fan every second hour when it is dark 
`if DateTime is dark and DateTime minutesS is 20 and DateTime is even_hour, turn Fan on` 

The built package is not tested, but I hope it works.
 ```{
    "name": "date-time-adapter",
    "display_name": "DateTime Adapter",
    "description": "A DateTime adapter to create more advanced rules",
    "version": "0.9.1",
    "url": "https://github.com/tomasy/date-time-adapter/releases/download/0.9.1/date-time-adapter-0.9.1.tgz",
     "api": {
      "min": 2,
      "max": 2
    }
}```

**Comment by mrstegeman** [comment]
This is very cool! A few things:

1. If you're going to use `bootstrap.py` (which I like), don't include the `lib` directory in your package.
2. In `DTFiveMinutesProperty`, you should decide between it being a string or a number/integer property. You can use `enum` in both cases, but if you're using a string property, it doesn't make sense to set a minimum and maximum.
3. `DateWeekendProperty` and `DTDarkProperty` should be `readOnly`.
4. The links in your `package.json` all just point to an empty github repo.

**Comment by tomasy** [comment]
Thanks for your feedback.
 1. I assume this part shall be remove from `bootstrap.py` ?
```try:
    sys.path.append(os.path.join(_BASE_DIR, 'lib'))

    import ephem  # noqa: F401
    import pytz     # noqa: F401

except ImportError:
    # If installation failed, exit with 100 to tell the gateway not to restart
    # this process.
    if not install_packages():
        sys.exit(100)
```
 2. About `DTFiveMinutesProperty` It is because of rule-engine. (I will remove minimum and maximum)
    * A string supports equal.
   * number support <, or > but not equal. 
   * Integer was my first chooice but it is not supported at all in in rule-engine My bug report https://github.com/mozilla-iot/gateway/issues/1456
   * Enum is not well suported. You have to type in th values in rule-engine like strings. My bug report https://github.com/mozilla-iot/gateway/issues/1457
  3. `DateWeekendProperty` and `DTDarkProperty` is changeable due to a bug in rule-engine. If you create a new rule with more than one input it will not trigger before a transition has been done. By making them read/writeable a transition can be done manually after the rule is created (or you have to wait up to one week if you are using `DateWeekendProperty` :-). My bug report  https://github.com/mozilla-iot/gateway/issues/1452
 4. I normally host my projects at my own git server. I have just uploaded release to github. Is this a problem?  It shall be possible to bug report at least.

English is not my native language so if you can help me with a short and clear explanation of the need to manually press `DateWeekendProperty` and `DTDarkProperty` after a rule is create with one of them. I would appreciate that. (Or at least the ev. user of it)

**Comment by mrstegeman** [comment]
1. No, keep that there. The point of the bootstrap script is to pull down the dependencies at runtime, rather than at build time, so that you don't have to bundle the pre-built libraries (which is important when there are compiled dependencies, as is the case with your add-on).
2. Fair enough. Removing `minimum` and `maximum` is fine.
3. Ah, I see. That's an unfortunate issue.
4. I'm fine with you hosting wherever you want. It would be nice to at least post the README to the github repo, though, that way when users click on the link from the add-ons page, they're not looking at an empty repo.

@hobinjk Do we have a good reason for mozilla-iot/gateway#1452, or was that an unintentional bug? I can see use cases both ways.

**Comment by tomasy** [comment]
1. Updated to 0.9.2
2. Removed lib in package
3. Removed enum, minimum and maximum for `DTFiveMinutesProperty`
4. Added README.md to github

**Comment by mrstegeman** [comment]
Thanks for all the fixes. I actually just noticed a couple other things.

1. `DTMinuteSProperty', `DTHourProperty`, and `DTFiveMinutesProperty` is a string property. That's fine, but `minimum` and `maximum` should be removed, as well as `@type`. `LevelProperty` requires a numeric value.
2. The device should probably just have an empty `@type` list (via `self._type`). It's not a sensor at all, so it doesn't make a lot of sense to represent it as one.
3. When loading the add-on, it fails because `requirements.txt` is not included in the package.

**Comment by mrstegeman** [comment]
`setup.cfg` is missing as well.

**Comment by tomasy** [comment]
But `LevelProperty` works with strings and maximum and minimum. I have experimneted a loot, trust me, because of the bugs in rule engine. I had prefered to use integer but...

And, but this is not a big issue, is this not a type of sensor? It is a sun sensor!?

**Comment by mrstegeman** [comment]
Once we get the bugs fixed, you can adjust the properties as necessary. Here's a link to the `LevelProperty` schema: https://iot.mozilla.org/schemas/#LevelProperty

Well............ not technically. It's only calculating things, not sensing. 😄 I don't have a major problem with the sensor schemas if you want to keep them, I just personally find it to be unintuitive.

**Comment by tomasy** [comment]
First, thanks for your support. Uploaded 0.9.3

I have added the missing files but I have not changed LevelProperty, minimum, maximum, because of the bug of missing integer. I will use integers when the bug is fixed.

**Comment by mrstegeman** [comment]
1. The adapter crashed on startup due to an invalid default timezone. If you modify the config in `package.json` and set timezone to `UTC`, this error goes away.
2. The `enabled` flag should not be set in your `package.json`.

Other than that, things look good. I'll merge when you get me an 0.9.4 release with those fixes.

**Comment by tomasy** [comment]
0.9.4 uploaded.

How do I test the installation? I have used you a lot.

**Comment by mrstegeman** [comment]
We'll get that fixed in the rules engine. If you find other places where `integer` is not properly supported, please file issues. It's supported by the W3C, so we should have full support as well.
