### ISSUE TITLE
[new addon] sound-player-adapter

### ISSUE THREAD

**Issue by lmnch** [mozilla-iot/addon-list#33]
I've created an adapter which can play sound files on a raspberry pi.
Can you add it?
```
{
    "name": "sound-player-adapter",
    "display_name": "Sound Player",
    "description": "A Mozilla IoT Adapter for playing soundfiles on a raspberry pi",
    "version": "0.1.1",
    "url": "https://github.com/lmnch/sound-player-adapter/releases/download/v0.1.1/sound-player-adapter-0.1.1.tgz",
     "api": {
      "min": 1,
      "max": 2
    }
}
```

**Comment by mrstegeman** [comment]
I'd be happy to add it, but first, you'll need to package it all together properly, including your `node_modules`. You might want to use something like this: https://github.com/mozilla-iot/philips-hue-adapter/blob/master/package.sh

**Comment by lmnch** [comment]
Thanks, I've packaged it together.
```
{
    "name": "sound-player-adapter",
    "display_name": "Sound Player",
    "description": "A Mozilla IoT Adapter for playing soundfiles on a raspberry pi",
    "version": "0.1.1",
    "url": "https://github.com/lmnch/sound-player-adapter/releases/download/v0.1.1/sound-player-adapter-0.1.1.tgz",
     "api": {
      "min": 1,
      "max": 2
    }
}
```

**Comment by benfrancis** [comment]
Hi @lmnch, thank you for the contribution.

I was just wondering, have you considered building your sound player as a separate native web thing which exposes the Web Thing API directly, rather than adding sound output to the gateway?

The gateway software is really intended to bridge IoT devices and protocols to the Web of Things, not as a basis for building devices by adding sensors and actuators to the gateway itself. You can think of the gateway as a headless hub or router, which provides a unified web interface for all your things.

We are currently in the process of writing a Things Framework to help people build their own native web things, like a Raspberry-pi based music player, by providing re-usable software libraries. Let us know if you'd be interested in building a music player web thing and how we can help.

**Comment by lmnch** [comment]
Thanks for the explanation.
I will see what I can do about the web thing.
